const express = require('express');
const router = express.Router();
const proyectoController = require('../controllers/proyectoController');
console.log(proyectoController);
const { verifyToken } = require('../middleware/authMiddleware');
const { verificarLiderDelProyecto } = require('../middleware/proyectoAccess');
const { conectarUsuarioOpcional } = require('../middleware/authOpcional');
console.log(typeof verifyToken);
router.post('/',verifyToken,proyectoController.createProyecto);
router.get('/:id',conectarUsuarioOpcional,proyectoController.getProyectoById);
router.put('/:id',verifyToken,proyectoController.updateProyecto);
router.get('/',proyectoController.obtenerTodosLosProyectos);
module.exports = router;